steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        exec uvicorn main:app --host=0.0.0.0 --port=$PORT

timeout: 900s
